### ISSUE TITLE
Webpage to control auto-reply modules

### ISSUE THREAD

**Issue by RaenonX** [RxJellyBot/Jelly-Bot#28]
## After #69  is completed
- [x] The webpage will list all the auto-reply modules including the inactive ones in a separate section. (#135)
- [x] Users can enter a keyword to limit their search for this list. Similar to the mechanism of `/info/<CHANNEL_OID>/msgstats/`. (#135)
- [x] (Active modules) Users can view its ~~usage statistics~~ called count (#135)
- [ ] (Active modules) Delete the module
- [ ] (Active modules, Creator only) Modify the content
- [ ] (Active modules, Creator only) Modify the properties
- [ ] Check if making modification is permitted by checking if the member is in the module original channel. (#33)
- [x] Calling `JC AR LIST` should give the link to this page. (#135)

**Comment by RaenonX** [comment]
JIRA:
- http://jira.raenonx.cc/browse/JB-10
- http://jira.raenonx.cc/browse/JB-11
- http://jira.raenonx.cc/browse/JB-12
- http://jira.raenonx.cc/browse/JB-13
